server:
  port: 8081
  ssl:
    enabled: false

spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: hello-server
          uri: https://spring.io/
          predicates:
            - Path=/hello
          filters:
            - RewritePath=/hello/(?<path>.*), /$\{path}
#        - id: preInc
#          uri: lb://preInc
#          predicates:
#            - Path=/preapp/**
#          filters:
        # - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

logging:
  level:
    org.springframework: INFO
    com.netflix: DEBUG

#ribbon.ConnectTimeout=1000000
#ribbon.ReadTimeout=60000